controller_list:
  - name: fake_manipulator_controller
    joints:
      - <robot_arm_joint_1>
      - <robot_arm_joint_2>
      - <robot_arm_joint_3>
  - name: fake_endeffector_controller
    joints:
      []
