# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed
# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  <manipulator_joint_1>:
    has_velocity_limits: <boolean>
    max_velocity: <value>
    has_acceleration_limits: <boolean>
    max_acceleration: <value>
  <manipulator_joint_2>:
    has_velocity_limits: <boolean>
    max_velocity: <value>
    has_acceleration_limits: <boolean>
    max_acceleration: <value>
  <robot_arm_joint1>:
    has_velocity_limits: <boolean>
    max_velocity: <value>
    has_acceleration_limits: <boolean>
    max_acceleration: <value>
  <robot_arm_joint2>:
    has_velocity_limits: <boolean>
    max_velocity: <value>
    has_acceleration_limits: <boolean>
    max_acceleration: <value>
  <robot_arm_joint3>:
    has_velocity_limits: <boolean>
    max_velocity: <value>
    has_acceleration_limits: <boolean>
    max_acceleration: <value>
